import './globals.css'
import MainComponent from './components/MainComponent'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

require('@solana/wallet-adapter-react-ui/styles.css');

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MainComponent>
          {children}
        </MainComponent>
      </body>
    </html>
  )
}
